spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_data?autoReconnect=true&useSSL=false
    username: productAdmin
    password: root

  #jpa settings
  jpa.hibernate.ddl_auto: create
  jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQLDialect